# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'OSMKitTests' do
  pod 'OSMKit-Swift/API', :path => '../OSMKit-Swift.podspec'
end

# Allow testing of OSMKit-Swift
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "OSMKit-Swift"
      target.build_configurations.each do |config|
        if config.name == "Debug"
            config.build_settings['ENABLE_TESTABILITY'] ||= "YES"
        end
      end
    end
  end
end
