language: objective-c
osx_image: xcode7.2

script:
  - pod install --project-directory=./OSMKit
  - xctool -workspace ./OSMKit/OSMKit.xcworkspace -scheme OSMKitTests -sdk iphonesimulator -arch i386 test
